apiVersion: v1
kind: Service
metadata:
  name: recipes-manager-service
  labels:
    {{- include "recipe-manager.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "recipe-manager.selectorLabels" . | nindent 4 }}
